// Define All Data Models Here

type ProductVariants = [
  sizes: string [], // sm, m, l, xl
  colors: string [] // black, white, etc
]

type Coupons = [
  coupon: {
    id: string,
    isActive: boolean,
    couponCode: string,
  }
]

export interface ShopOwner {
  id: string;
  name: string;
}

export interface Product {
  id: number;
  name: string;
  vendor: ShopOwner;
  description: string;
  price: number;
  // quantity: number;
  slug: string; // generated by useMakeSlug Hook!
  variants: ProductVariants[];
  image1_Url: string;
  image2_Url: string;
  rating: number;
  reviewsCount: number; // reviews type???
  InStockCount: number;
  coupons: Coupons[];
  category: string; // grab from predefined categories
  isFeatured: boolean;
  tags: string [];
  brand: string;
}